name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  test:
    name: RabbitMQ ${{ matrix.rabbitmq }}, Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "4.0"
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        rabbitmq:
          - "4.2"
          - "4.1"
          - "4.0"
          - "3.13"

    env:
      CI: true

    services:
      rabbitmq:
        image: rabbitmq:${{ matrix.rabbitmq }}-management
        ports:
          - 5672:5672
          - 15672:15672
        options: --name rabbitmq

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Wait for RabbitMQ to start
        run: sleep 10

      - name: Set up RabbitMQ
        run: ./bin/ci/before_build_docker.sh

      - name: Run tests
        run: bundle exec rspec spec

  test_all:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test (matrix)
    needs: test
    steps:
      - name: Check test matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
